version: '3'
services:
  example:
    image: 'magento/magento-cloud-docker-php:8.2-cli-1.3.5'
    volumes:
      - '.:/app:delegated'
    environment:
      - 'PHP_EXTENSIONS=bcmath bz2 calendar exif gd gettext intl mysqli pcntl pdo_mysql soap sockets sysvmsg sysvsem sysvshm opcache zip xsl sodium xdebug'
      - XDEBUG_MODE=coverage
